#!/usr/bin/env python3
"""Compile SKILL.md files into Cursor .mdc rule files.

Cursor reads rules from a flat directory of .mdc files (not subdirectories),
so SKILL.md folders must be compiled rather than symlinked.

Reads [cursor_targets.<name>] from skills-sync.toml. Each entry has a path
and an optional skills allowlist:

  [cursor_targets.cursor-user]
  path = "~/.cursor/rules"
  skills = ["virt-graph"]   # optional — omit to compile all skills

  - '~' is expanded to the user's home dir.
  - Relative paths resolve against the current working directory at
    invocation time (so project-scoped targets follow you into whichever
    project you cd into).
  - If `skills` is set, only those skill names are compiled/cleaned for
    that target. Skills not in the list are silently ignored.

Subcommands:
  status   show whether each skill is up to date, missing, stale, or foreign.
  compile  generate (or regenerate) .mdc files from SKILL.md (idempotent).
  clean    remove .mdc files that were generated by this script.

Output format:
  Each SKILL.md is compiled to <skill-name>.mdc with Cursor-compatible
  frontmatter: description (from frontmatter), alwaysApply: false (skills
  are agent-requested, not always injected), and the SKILL.md body verbatim.
  A YAML comment marks the file as ours so status/clean can identify it.

Safety:
  - Never touches .mdc files it did not generate (marked "foreign").
  - compile skips foreign files and reports a conflict.
  - clean skips foreign files silently.
  - --dry-run prints actions without writing anything.
"""

from __future__ import annotations

import argparse
import os
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO_ROOT / "skills"
CONFIG_FILE = REPO_ROOT / "skills-sync.toml"

# Written as a YAML comment in every .mdc we generate.
# Used by status/clean to identify our files vs foreign ones.
GENERATED_MARKER = "skills-repo:generated"


@dataclass
class CursorTarget:
    name: str
    path: Path
    allowlist: list[str] | None  # None = all skills; list = only these names


def load_target(name: str) -> CursorTarget:
    if not CONFIG_FILE.exists():
        sys.exit(
            f"No config at {CONFIG_FILE.relative_to(REPO_ROOT)}. "
            f"Copy skills-sync.example.toml to skills-sync.toml and edit it."
        )
    cfg = tomllib.loads(CONFIG_FILE.read_text("utf-8"))
    entry = cfg.get("cursor_targets", {}).get(name)
    if not entry:
        available = ", ".join(cfg.get("cursor_targets", {}).keys()) or "(none)"
        sys.exit(f"Unknown cursor target '{name}'. Available: {available}")
    raw = entry.get("path")
    if not raw:
        sys.exit(f"Target '{name}' is missing 'path'.")
    expanded = Path(os.path.expanduser(raw))
    if not expanded.is_absolute():
        expanded = Path.cwd() / expanded
    allowlist = entry.get("skills")  # list[str] or None
    return CursorTarget(name=name, path=expanded.resolve(), allowlist=allowlist)


def list_skills() -> list[Path]:
    if not SKILLS_DIR.exists():
        return []
    return sorted(
        p for p in SKILLS_DIR.iterdir() if p.is_dir() and not p.name.startswith(".")
    )


def _skill_harnesses(skill: Path) -> set[str] | None:
    """Return the harnesses set from SKILL.md frontmatter, or None (= all harnesses).

    SKILL.md frontmatter format:
      harnesses: [databricks, claude-code, codex, cursor]

    When the field is absent, the skill is included everywhere (default behaviour).
    """
    skill_md = skill / "SKILL.md"
    if not skill_md.exists():
        return None
    text = skill_md.read_text("utf-8")
    if not text.startswith("---"):
        return None
    try:
        end = text.index("---", 3)
    except ValueError:
        return None
    for line in text[3:end].splitlines():
        k, sep, v = line.partition(":")
        if sep and k.strip() == "harnesses":
            raw = v.strip().strip("[]")
            return {h.strip() for h in raw.split(",") if h.strip()}
    return None


def _filter_skills(skill_filter: str | None, allowlist: list[str] | None) -> list[Path]:
    skills = list_skills()
    if allowlist is not None:
        skills = [s for s in skills if s.name in allowlist]
    # Respect SKILL.md harnesses field — omit skills not targeting cursor.
    skills = [s for s in skills if (h := _skill_harnesses(s)) is None or "cursor" in h]
    if skill_filter:
        skills = [s for s in skills if s.name == skill_filter]
        if not skills:
            sys.exit(f"No skill named '{skill_filter}' under {SKILLS_DIR.relative_to(REPO_ROOT)}.")
    return skills


def _parse_skill_md(skill: Path) -> tuple[dict[str, str], str]:
    """Parse SKILL.md. Returns (frontmatter_dict, body_text)."""
    skill_md = skill / "SKILL.md"
    if not skill_md.exists():
        sys.exit(f"Missing SKILL.md in {skill.relative_to(REPO_ROOT)}.")
    text = skill_md.read_text("utf-8")
    if not text.startswith("---"):
        return {}, text
    end = text.index("---", 3)
    fm_block = text[3:end].strip()
    body = text[end + 3:].strip()
    fm: dict[str, str] = {}
    for line in fm_block.splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip()
    return fm, body


def _dest_path(target: CursorTarget, skill: Path) -> Path:
    fm, _ = _parse_skill_md(skill)
    name = fm.get("name", skill.name)
    return target.path / f"{name}.mdc"


def _build_mdc(fm: dict[str, str], body: str, skill: Path) -> str:
    """Render the .mdc content for a skill.

    Replaces agent-harness-specific script paths (e.g. `.claude/skills/<name>/`)
    with absolute paths to the canonical skill directory in this repo, so the
    compiled .mdc works from any project regardless of harness.
    """
    description = fm.get("description", "")
    # Escape double quotes inside the YAML string value.
    description_escaped = description.replace('"', '\\"')
    # Substitute .claude/skills/<name>/ → absolute path in this repo.
    # SKILL.md is authored with Claude Code paths as the primary harness;
    # the compiled .mdc must be self-contained for any agent/project.
    body = body.replace(
        f".claude/skills/{skill.name}/",
        str(skill.resolve()) + "/",
    )
    lines = [
        "---",
        f'description: "{description_escaped}"',
        "alwaysApply: false",
        f"# {GENERATED_MARKER}",
        "---",
        "",
        body,
        "",  # trailing newline
    ]
    return "\n".join(lines)


def _is_ours(dest: Path) -> bool:
    """True if the .mdc file was generated by this script."""
    if not dest.exists():
        return False
    return GENERATED_MARKER in dest.read_text("utf-8")


def classify(skill: Path, target: CursorTarget) -> str:
    """Return one of: missing | current | stale | foreign."""
    dest = _dest_path(target, skill)
    if not dest.exists():
        return "missing"
    if not _is_ours(dest):
        return "foreign"
    fm, body = _parse_skill_md(skill)
    if dest.read_text("utf-8") == _build_mdc(fm, body, skill):
        return "current"
    return "stale"


# ── subcommands ────────────────────────────────────────────────────────────


def cmd_status(target: CursorTarget, skill_filter: str | None) -> int:
    skills = _filter_skills(skill_filter, target.allowlist)
    print(f"Target: {target.name} → {target.path}")
    if not target.path.exists():
        print("  (target directory does not exist yet)")
    for skill in skills:
        state = classify(skill, target)
        dest = _dest_path(target, skill)
        print(f"  {skill.name:<30}  {state:<10}  ({dest.name})")
    return 0


def cmd_compile(target: CursorTarget, skill_filter: str | None, dry_run: bool) -> int:
    skills = _filter_skills(skill_filter, target.allowlist)
    if not target.path.exists():
        print(f"{'Would create' if dry_run else 'Creating'} target dir: {target.path}")
        if not dry_run:
            target.path.mkdir(parents=True, exist_ok=True)

    print(f"Target: {target.name} → {target.path}")
    exit_code = 0
    for skill in skills:
        state = classify(skill, target)
        dest = _dest_path(target, skill)
        if state == "current":
            print(f"  {skill.name}: up to date ({dest.name})")
        elif state == "foreign":
            print(
                f"  {skill.name}: CONFLICT — {dest.name} exists but was not generated "
                "by this script. Remove it manually first."
            )
            exit_code = 1
        else:
            fm, body = _parse_skill_md(skill)
            content = _build_mdc(fm, body, skill)
            if dry_run:
                print(f"  {skill.name}: would write {dest.name} ({state})")
            else:
                dest.write_text(content, encoding="utf-8")
                print(f"  {skill.name}: wrote {dest.name} ({state})")
    return exit_code


def cmd_clean(target: CursorTarget, skill_filter: str | None, dry_run: bool) -> int:
    skills = _filter_skills(skill_filter, target.allowlist)
    print(f"Target: {target.name} → {target.path}")
    for skill in skills:
        dest = _dest_path(target, skill)
        if not dest.exists():
            print(f"  {skill.name}: not present ({dest.name})")
        elif _is_ours(dest):
            if dry_run:
                print(f"  {skill.name}: would remove {dest.name}")
            else:
                dest.unlink()
                print(f"  {skill.name}: removed {dest.name}")
        else:
            print(f"  {skill.name}: not ours — leaving alone ({dest.name})")
    return 0


# ── entry point ────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Compile SKILL.md files into Cursor .mdc rule files."
    )
    parser.add_argument("command", choices=["status", "compile", "clean"])
    parser.add_argument(
        "--target", "-t", required=True,
        help="Named cursor target from skills-sync.toml.",
    )
    parser.add_argument(
        "--skill", "-s",
        help="Operate on one skill by name. Default: all skills in skills/.",
    )
    parser.add_argument(
        "--dry-run", "-n", action="store_true",
        help="Print what would happen; don't write or delete anything.",
    )
    args = parser.parse_args()

    target = load_target(args.target)

    if args.command == "status":
        return cmd_status(target, args.skill)
    if args.command == "compile":
        return cmd_compile(target, args.skill, args.dry_run)
    if args.command == "clean":
        return cmd_clean(target, args.skill, args.dry_run)
    return 1


if __name__ == "__main__":
    sys.exit(main())
